### ISSUE TITLE
sliding buttons out of screen

### ISSUE THREAD

**Issue by toby-bro** [jrpie/Launcher#10]
**Describe the bug**
The sliding buttons happen not to be completely in the expected space.

**To Reproduce**
1. Go to settings
2. See error

**Expected behavior**
This is a bug that I already had with Finn's app but that I never took the time to solve. 

**Screenshots**
![Screenshot_20240827_002616_Launcher](https://github.com/user-attachments/assets/d1bc1eb9-4085-4792-a538-7462973c167a)

**Smartphone (please complete the following information):**
 - Device: Samsung S20
 - Android Version: Android 13 One UI 5.1

**Additional info**
Quite a minor bug in the global user experience. Thanks.

**Comment by toby-bro** [comment]
By the way I'll probably do a MR to improve the french translations as I mentionned on discord. I guess you're right french is not length efficient (I'll try and remember if I want to save money whilst using chatgpt).

**Comment by jrpie** [comment]
That would be very nice!

**Comment by jrpie** [comment]
FYI: yzqzss has a weblate at https://toolate.othing.xyz/projects/jrpie-launcher/
