### ISSUE TITLE
Favorite apps

### ISSUE THREAD

**Issue by NicolasGuruphat** [jrpie/Launcher#14]
Hello !
First of all y our launcher is really cool ! But, in my opinion, it misses one feature that could be really helpful. As you have a restreint choice of application to bind on the main page, there could be some app that you want to keep on hand but that are not important enough to be binded to one of the control. So I think that a system of favorite applications, that just put the app at the begining of the list, would be super cool !

**Comment by jrpie** [comment]
Thank you for the suggestion!
In my opinion having favorites pinned to the top of All Apps would clutter the list too much.
The intention for All Apps is to search the entire system efficiently. Especially when searching it is not clear how to handle favorites. 

I'd prefer adding a second list, Favorite Apps, working similarly as All Apps, which users can then bind to any gesture they like (i.e. bind swipe up to favorite apps and swipe up on left edge to all apps).

Would that fit your use case?

**Comment by jrpie** [comment]
I like the idea of having a button to go from favorite apps to all apps 👍🏼 That way a users can decide not to bind all apps to any gesture at all and still access that through favorites.

I'm not too sure about the reverse though. Where should such a button go? At the top it clutters the list (not as badly as a long list of favorite apps pinned there, but might still be annoying for users who don't want to use favorites at all).  At the bottom such a button feels out of place (who would want to scroll through all apps in order to get to favorites?)

**Comment by NicolasGuruphat** [comment]
Maybe the favorite app page could look just like the application page but with "Favorite" instead of "Applications" at the top, and when you click on the "Favorite" title it goes to all applications page (and the opposite too : if you're in all Applications and you click the title, it goes to the favorites page).
I'm not super sure about this idea, maybe it will not be intuitive, but it sounds cool in my head lol.

**Comment by wassupluke** [comment]
Adding to the idea pile: add a ⭐ icon to the right end of the search bar of the All Apps menu to narrow the list (and the apps automatically launched by the "Launch search results" feature), and the reverse would be the star changes to a home icon that allows the user to widen the menu list and launchable apps to everything again.

**Comment by jrpie** [comment]
Sounds good! I was thinking about adding a button to the bottom oft the list, but i think an icon is much better.

I don't really like the loss oft symmetry though. One icon on the left and one on the right is definitely looks nicer. But usability is definitly more important.

**Comment by jrpie** [comment]
What about adding the button to the right of the search bar? That way the title would still be symmetrical

**Comment by jrpie** [comment]
Unfortunately I don't really have time to work on the app this week, but this feature is the one I want to implement next

**Comment by wassupluke** [comment]
![Screenshot_20240916-093530.png](https://github.com/user-attachments/assets/58e3a916-479c-4b5d-8dfd-baaf50883fdf)

On my end there's the search icon on the left, so the star/home icon on the right shouldn't really affect the symmetry (I agree that keeping the text symmetry is important). Just started using your launcher but it's by far the easiest to use and most functional/aesthetic minimalist launcher I've ever used. The gesture launches for apps are heavenly.

**Comment by jrpie** [comment]
Oh, sorry, I somehow thought you were suggesting to add it to the top (i.e. next to the title "all apps"), but you clearly wrote _search_ bar not title bar. So I just misunderstood the idea and then suggested the same thing ^^ Sorry for the confusion.

**Comment by jrpie** [comment]
> ![Screenshot_20240916-093530.png](https://private-user-images.githubusercontent.com/16409758/367823294-58e3a916-479c-4b5d-8dfd-baaf50883fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDU0MzMsIm5iZiI6MTcyNjUwNTEzMywicGF0aCI6Ii8xNjQwOTc1OC8zNjc4MjMyOTQtNThlM2E5MTYtNDc5Yy00YjVkLThkZmQtYmFhZjUwODgzZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE2NDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYmNkMDRiMDc1YzMzMTlkY2I1MWIxMTI0NTJhNjk3N2M1NTE5NDBhYzYxOWViOTY2Zjk5OThkNmY0MjY0YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L_3htIgdaQvxMBQeak2FC6rDocg7NE8sUkNe7FxrP50)
> 
> Just started using your launcher but it's by far the easiest to use and most functional/aesthetic minimalist launcher I've ever used. The gesture launches for apps are heavenly.

Thanks, nice to hear that!
You should rather thank @finnmglas for that though as he built the original version of Launcher. I just saw some room for (subjective) improvements.
