### ISSUE TITLE
[Feature Request] Option to hide apps

### ISSUE THREAD

**Issue by urmomseksy** [jrpie/Launcher#15]
Please add an option to hide apps from the All Applications list with an option to temporarily unhide as needed.

Thanks.

**Comment by jrpie** [comment]
Thank you for the suggestion.
I'd prefer if All Apps actually does what its name says it does, especially since another list, say "Really all apps", would be required to unhide apps again.

What exactly are you trying to accomplish with this feature? Would something like [this suggestion](https://github.com/jrpie/Launcher/issues/14#issuecomment-2323023598) work for you?

If you have a set of time-eating apps, say social media, which you don't want to see all the time,
what about using [Shelter](https://f-droid.org/packages/net.typeblog.shelter/) to move those to the work profile?

**Comment by urmomseksy** [comment]
My primary use case would be to hide uninstallable system apps from the scrolling list of all apps as well as the search results. It is more for decluttering and limiting search results than anything. 

A launcher such as KISS lets you hide the app separately from everything or allows it to still show up in the search if wanted.

Off topic: to be honest, I would love if you forked KISS and just made more gestures than what the app currently allows. Either way, I think it would possibly give you inspiration for features you might want if you played around with the app. It's obviously all whatever you choose to do. I really appreciate what you have done with this app so far.

https://github.com/Neamar/KISS

Thanks again.

**Comment by jrpie** [comment]
I see, uninstallable unwanted system apps are a problem. Then implementing this is probably worthwhile. I'm still thinking about the UI for unhiding.

**Comment by jrpie** [comment]
KISS looks quite nice!

However for this app I'd like to stick to the idea of having an extremely minimalistic home screen where gestures are  the main mode of interaction.

**Comment by toby-bro** [comment]
Yep, that implies that one day all the bugs will be fixed and all the features implemented and the only objective will be following android releases for deprecations. 

Concerning the UI, I thought maybe the simplest option would be a switch 'show all apps' and adding in the drop down menu of the app a hide / unhide checkbox 🤷

**Comment by jrpie** [comment]
> Concerning the UI, I thought maybe the simplest option would be a switch 'show all apps' and adding in the drop down menu of the app a hide / unhide checkbox 🤷

I also thought about this. What I don't like about the drop down menu approach is that a user might accidentally hide an app and then does not know where to unhide it again.

I think it would be best to have a button "Manage hidden apps" in settings. Clicking this should open a list of all apps together with checkboxes to toggle the hidden state. That way both operations are in the same place.

Similarly, "Manage favorite apps" (see #14 ) might be implemented. (For favorites this is not as much of a problem as for hiding, but I think it would be nice if both worked in a similar way).

**Comment by wassupluke** [comment]
## Re-open?
Could we reopen this to work on implementing
> [an option to temporarily unhide as needed](https://github.com/jrpie/launcher/issues/15#issue-2498792090)

and
> [the UI for unhiding](https://github.com/jrpie/launcher/issues/15#issuecomment-2323057003)

## Use case
Yesterday I wanted to pull up Nova Launcher to look at their gesture use again but this app is one I have "hidden". To launch it I would have to go to uLauncher Settings>Launcher>Hidden apps>and launch it from there. Don't get me wrong, I love that I can hide stuff to simplify my list of apps, but that's a crap ton of steps just to get access to an app I have installed on my phone. :p

## Potential solution
- Maybe access hidden apps from the main launcher by prepending "h " to the search query
  - similar to how prepending " "(space) activates web searching 
- And / Or make the magnifying glass a clickable element that populates the full list of all apps on the device
  - this would let you to use the magnifying glass icon as one uses a magnifying glass IRL to take a closer look at things (show all apps)

Thoughts?

**Comment by jrpie** [comment]
I still don't understand why you want to hide such an app in the first place. The idea of the list is to manage the chaos by searching. Hidden apps were only added to allow people to hide uninstallable bloatware (i.e. stuff they _never_ use).
I don't want µLauncher to turn into something where people spend hours tagging and categorizing their apps and this feature (apps that are hidden but still somewhat accessible) would be another step in that direction. On the other hand this request keeps coming up.
I think the right place to discuss this is #84
