### ISSUE TITLE
[Feature Request] Option to not show keyboard immediately when going to Application list

### ISSUE THREAD

**Issue by urmomseksy** [jrpie/Launcher#16]
Currently when you try to view all applications, the keyboard immediately pops up and you can't view the list until you minimize the keyboard. Please add an option to not show the keyboard immediately and only show it if you click in a search box.

**Comment by jrpie** [comment]
Thank you for the suggestion! This is already implemented (settings > launcher > functions > start keyboard for search). However an option is of course useless, if users can't find it.
The naming is probably not optimal, especially "functions". Perhaps "Functionality" would be better or I could add a dedicated section for the "All Apps" screen.

Was the naming the problem or did you not find the settings screen at all?

**Comment by urmomseksy** [comment]
![Screenshot_20240831_130617_Launcher](https://github.com/user-attachments/assets/0ac65abb-e659-4a8e-8ddb-02b0ca9664a2)

There is no toggle button in the settings, although it looks like it was intended.

See attached.

**Comment by toby-bro** [comment]
Hey there, I think the fact that there is no toggle button is corrected in https://github.com/jrpie/Launcher/commit/62c6e1fc2f89ee07e9ffa7607c0c84825d3c0906 It will be corrected in the version j-0.0.9 of the app.

**Comment by urmomseksy** [comment]
Oh, okay. I am sure you are right because I noticed that the version on the Play store is higher than fdroid. I'll close this and could reopen it later if something doesn't work right with the original issue.

**Comment by jrpie** [comment]
> Edit: thank you so much for this launcher. This is exactly how I want to use my phone. With just a few improvements it will be nearly perfect for me.

You should thank Finn, he did most of the work, I only made some improvements 😅 


> I think your naming of the settings is good.

Maybe "Functionality" might be better instead of "Functions" (?)

**Comment by urmomseksy** [comment]
Functionality might be slightly better than Functions, but I don't think the naming as it is now would be confusing to anybody. 

From what I saw, I thought most of the settings in English look pretty good as far as how you labeled and named them.
