### ISSUE TITLE
[Feature Request] instantaneous search 

### ISSUE THREAD

**Issue by urmomseksy** [jrpie/Launcher#18]
Currently when searching for an app, you have to press enter to see the app.

It would be nice if search results populated instantly while typing while the keyboard is active on the screen.

~~It would also be a bonus if there was an option to launch the first app that populates the search when hitting enter instead of having to the tap on it.~~

**Comment by toby-bro** [comment]
Concerning the first request, I think there is an option that does this by default : `Launch Search Results` but maybe I did not understand your problem.

By the way if this is indeed the solution to your problem, and you find the name inappropriate, how would you rename this option ?

**Comment by urmomseksy** [comment]
You are right, I did miss the setting. So I guess if that setting stayed in place while being able to do the other stuff, that would be awesome. 

So basically the only thing from my original request that I would still request is that search results populate instantly. When I'm typing an app name, I don't actually see the app show up until I hit enter.

**Comment by toby-bro** [comment]
Okay, I think this might be related to #9 which has also been corrected in j-0.0.9
Try deactivating full screen mode until the update (I don't know why f-droid is so slow as it knows that there has been a new release since two days : https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.jrpie.android.launcher.yml)

**Comment by urmomseksy** [comment]
Thank you so much. I didn't realize it was a bug. I thought it was a needed feature. Disabling full screen fixed the issue.
