### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by jrpie** [jrpie/Launcher#2]
Themes are currently broken. [DynamicColors](https://developer.android.com/develop/ui/views/theming/dynamic-colors) would be nice.

**Comment by jrpie** [comment]
Maybe add more clockfaces (requested by Niteesh Khanal)

**Comment by jrpie** [comment]
Add option to select different fonts (or follow the system default). Any suggestions?

**Comment by toby-bro** [comment]
I would find it indeed cool to be able to have the system font as a possibility, also shouldn't be to hard to do. 
Chosing from a list of preinstalled fonts could be an idea, but which fonts should be added ?

**Comment by jrpie** [comment]
Android has default fonts for serif, sans-serif, monospace and monospace-serif, I just added all of those (32c3c412).

**Comment by jrpie** [comment]
I implemented most of what I wanted in 99acdba2, themes should now be working.

Dynamic Colors are not implemented yet, so I opened #31 for that.
