### ISSUE TITLE
[Bug] When installing j-0.0.9, the installation splash screen and tutorial still show 0.0.8

### ISSUE THREAD

**Issue by urmomseksy** [jrpie/Launcher#26]
**Describe the bug**
I uninstalled 0.0.8 and installed 0.0.9 from GitHub APK, and the tutorial and set up screen still show 0.0.8. 

(It's pretty minor, but I thought it's worth pointing out)
![Screenshot_20240901_111454_Launcher](https://github.com/user-attachments/assets/565864fe-70a1-4dc8-b692-1bf4063c6f22)

**Comment by jrpie** [comment]
Quite embarrassing... Thanks for reporting this. I'm not entirely sure how this happened. Probably I didn't do a clean build and a cached value of `de.jrpie.android.launcher.BuildConfig` was used. When doing a clean build the value is correct. I just uploaded a new build of j-0.0.9 to the releases section.
