### ISSUE TITLE
[bug] Assigned button actions will not show the icon

### ISSUE THREAD

**Issue by urmomseksy** [jrpie/Launcher#27]
Probably related to #8 

To reproduce: 
- uninstall old launcher version 
- reinstall latest j-0.0.9 APK from GitHub 
- set as default launcher 
- go through the welcome screens without changing anything (there's an option on one of the welcome screens to change settings there but I skipped doing that).
- after the welcome screens are scrolled through, attempt to assign actions for "swipe right top," "swipe right bottom," and "double right."
- **after assigning the above actions, the actions work but the icons don't show up**

I attempted to turn off edge swipe actions and double swipe actions, then reenable them, but the icons still won't show up.

There were some other odd things going on with the icons, similar to above, which I'll attempt to describe after troubleshooting some more.

**Edit: another odd thing is that on a fresh install (and possibly on a non fresh install), when you click the X to remove the "volume up" action it will also remove the icon for "long click action."**

(I hope I'm clear above. For privacy reasons I would rather not attach a screen recording showing my apps list.)

**Comment by jrpie** [comment]
Probably this is identical to #8
I have seen this behavior before, but it is hard to reproduce the bug (at least on my device / emulators).
Do the icons show up eventually (i.e. after closing and reopening settings or force stopping Launcher)?

**Comment by urmomseksy** [comment]
> Probably this is identical to #8 I have seen this behavior before, but it is hard to reproduce the bug (at least on my device / emulators). Do the icons show up eventually (i.e. after closing and reopening settings or force stopping Launcher)?

I could not get the icons to show up again in a _consistent_ way. Force stopping the launcher, clearing cache, nothing seems to really work well (and I don't believe these worked at all). But, I would have some icons spontaneously reappear after I deleted the actions/icons on some other gestures. 

It's complicated to describe because it's hard to find the pattern to performing an action which makes something else happen.
