### ISSUE TITLE
New settings lagging on opening

### ISSUE THREAD

**Issue by toby-bro** [jrpie/Launcher#32]
**Describe the bug**
When opening the new settings there is a whole second before it realizes the keyboard is deactivated (or so I think this is the problem because it is not full screen straight away

**To Reproduce**
- go to settings (cf video)

**Comment by toby-bro** [comment]
https://github.com/user-attachments/assets/0b9e39c7-4aeb-4bcd-a55d-ab2cac82d1c8

**Comment by jrpie** [comment]
Thanks for reporting! Does the lag still appear when setting background to "solid"?
"Blur" is quite CPU intensive, maybe not a good default
(especially since most people probably use a single color background with this app)

**Comment by toby-bro** [comment]
whereas the background is dim, blur or solid the behaviour is exactly the same
