### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [jrpie/Launcher#39]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7818134941#L786

you tagged https://github.com/jrpie/Launcher/releases/tag/j-0.0.10 from https://github.com/jrpie/Launcher/commit/dddc2827b3e2ab7861f078c302ec4ba0265e9287

but the APK was built from the tree at https://github.com/jrpie/Launcher/commit/435250d7046aa444dfe9721e5442991ad57504d3 ?

we understand you need to test your commits, but please, when you release, build the APK from the tagged commit, and upload that one, not random older APKs you have around

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/21ac51e5110653f9feadcf9b280df5dfa2d39102

**Comment by jrpie** [comment]
I'm sorry. I was in a hurry yesterday and wanted to get the latest bugfixes out before going to bed.

So to save time, I started the build, wrote the changelog in the meantime, then commited `ddc282` and tagged it (not knowing that the current commit hash makes it into the apk). I guess I should automate the release process; doing that manually is too error prone. (And I really shouldn't work when I'm tired).



> /LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/21ac51e5110653f9feadcf9b280df5dfa2d39102

Is it better to upload a new apk for the release (just did that) and then open a merge request against fdroid-data to remove the `disabled`  field or should I just create a new release?

**Comment by licaon-kter** [comment]
I checked and reenabled: https://gitlab.com/fdroid/fdroiddata/-/commit/1c9a78597119b956c8d1779f020305f874eaf253 :tada:
