### ISSUE TITLE
[feature] option to hide app icons

### ISSUE THREAD

**Issue by jrpie** [jrpie/Launcher#42]
requested by @straycosmicllama in #41

**Comment by jrpie** [comment]
Thinking about this some more, it might be better to let users select from a list of predefined layouts instead of adding options like "hide icons". I think this is preferable since e.g. "text only" will need special of of notification dots and work profile indicator badges.

Some ideas:

**Default**:
![image](https://github.com/user-attachments/assets/daafa152-42e1-498d-ab46-cde7e0205f96)

**Text**:
![image](https://github.com/user-attachments/assets/4aeb6a8b-25b1-483b-8843-4e65e639c41e)
or even
**Grid**:
![image](https://github.com/user-attachments/assets/368d91d9-154e-4258-9df8-add958caab7a)

**Comment by apprehensions** [comment]
+1

**Comment by jrpie** [comment]
Implemented in 172de1f3ddfa94a4f717e0b3afc06ab8682766c2
