### ISSUE TITLE
Apps tray closes when swiped to in Landscape

### ISSUE THREAD

**Issue by Elf3874** [jrpie/Launcher#48]
**Describe the bug**
When swiping down to the Apps tray in landscape mode, the Apps tray closes.

**To Reproduce**
1. Go to the homescreen
2. Lay your phone sideways (to activate landscape)
3. Swipe down to the Apps tray

**Expected behavior**
When doing step 3, it should show the Apps tray in landscape for a second before closing automaticly.

**Smartphone (please complete the following information):**
 - Device: Fairphone 5
 - Android Version: 14

**Additional info**
- Automatic rotate needs to be enabled in your phone settings or notification tray.
- Running CalyxOS

**Comment by jrpie** [comment]
Thank you for reporting this! Unfortunately I can not reproduce the bug.

Just to clarify: When in landscape the app list immediately closes?
Does this also happen when "start keyboard for search" is off?

Could you please send a screen recording and/or a log from when the error occurs?
What version of the app are you using?

**Comment by Elf3874** [comment]
I don't have 'start keyboard for search' .
Version:  j0.0.10

Maybe these instructions are better:
First go to the homescreen, then put your phone in landscape and then you can swipe the direction you have set to the app tray.
You will see the app tray in landscape and it closing immediately after.


https://github.com/user-attachments/assets/2ac9a291-bddc-4000-9f2e-03fa73aca1d7

**Comment by jrpie** [comment]
Thanks! This looks very weird. How do you get the app to a state where the home screen is in portrait mode but the list comes up rotated? Is that using some Calyx-specific functionality?

**Comment by jrpie** [comment]
I get the following behavior, which is what should be expected (note that the home screen rotates):
[Screen_recording_20241004_141628.webm](https://github.com/user-attachments/assets/4cf21143-9d4d-427c-8c6d-ceb81d581e6d)

Changing the app such that the home screen is locked to portrait, I get the following, which also seems to work fine:
[Screen_recording_20241004_141937.webm](https://github.com/user-attachments/assets/770774a4-7f73-4bef-ae2e-e1fc5e132aae)

**Comment by jrpie** [comment]
It looks like Calyx tries to enable rotation by itself.

You didn't enable rotation in µLauncher settings (Settings icon in the top of the apps tray > Launcher > Display > Rotate Screen), right? Could you check that everything works fine when setting this option?

So µLauncher tells the API that it wants to stay in portrait but Calyx is like "let's go to landscape anyway".

**Comment by Elf3874** [comment]
> It looks like Calyx tries to enable rotation by itself.
> 
> You didn't enable rotation in µLauncher settings (Settings icon in the top of the apps tray > Launcher > Display > Rotate Screen), right? Could you check that everything works fine when setting this option?
> 
> So µLauncher tells the API that it wants to stay in portrait but Calyx is like "let's go to landscape anyway".

By the looks of it was it due to 'Rotate screen' being disabled, enabling it fixed the bug and lets the homescreen rotate.

But weird that it rotates the app tray with 'Rotate screen' disabled.

**Comment by jrpie** [comment]
Debugging this further, it looks like the OS tries to initially start the activity in landscape and then switches to portrait later. For this, the activity is recreated causing it to close (see [onPause()](https://github.com/jrpie/Launcher/blob/88e13c04d18c29771f07284e7ace4ac4e6ca1a2e/app/src/main/java/de/jrpie/android/launcher/ui/list/ListActivity.kt#L109), this is used to close the list when the user navigates to recents or launches an app)

**Comment by jrpie** [comment]
> But weird that it rotates the app tray with 'Rotate screen' disabled.

Yes, that is definitely a bug.

**Comment by jrpie** [comment]
I wrote a fix. However there is still a rotation animation (the activity start in the wrong orientation and is then rotated). It looks like there is no good way to force a screen orientation programatically.
Hardcoding it in the manifest works (but then there can't be an option for this).
I guess I should enable rotation by default (or maybe remove the setting entirely)
