### ISSUE TITLE
Is it safe to tap on “Uninstall App” of a system app?

### ISSUE THREAD

**Issue by GrimPixel** [jrpie/Launcher#5]
It is possible to see prompts for uninstalling system apps like “Camera”, “Clock”, “Contacts”. Would it break anything if I tapped on “Uninstall”?

**Comment by jrpie** [comment]
That is definitely a bug, thankts for pointing it out! The system won't let you uninstall system apps (i.e. it is safe to tap "uninstall", it just won't do anything), but the option really just should not show up in the first place.
I'm currently on vacation and will fix it once I'm back home.
