### ISSUE TITLE
[feature] add action: sleep

### ISSUE THREAD

**Issue by RizkyM2999** [jrpie/Launcher#51]
It would be perfect if it had double tap to sleep..

**Comment by jrpie** [comment]
Thanks for the suggestion! I think the best way to implement this would be to add a new action, which can then be bound to any gesture. I changed the name of the issue accordingly as there is nothing special to double tap.

**Comment by jrpie** [comment]
Unfortunately this is not quite as trivial as it might seem on first glance, since the app needs to be a device admin in order to be able to lock the device. Might take a while until I have time to implement this.
