### ISSUE TITLE
Question: how double thing work

### ISSUE THREAD

**Issue by BANOnotIT** [jrpie/Launcher#53]
I don't really get how to invoke those "Double up" thing. Can you explain that part?

**Comment by jrpie** [comment]
It means swiping with two fingers. I'm not too happy about the wording (also in other translations), maybe "two fingers up" might be better (?) Any other suggestion?

The proplem is that the label needs to be somewhat short in order to fit an small screen. Another suggestion would be to keep the current labels and add an info icon with a more verbose description.

**Comment by BANOnotIT** [comment]
Yeah, icon might be a cheap but useful solution.

Also I checked others and they provide animations explaining some mechanics. I reckon these animations are much harder to implement, but I think that'll be the most helpful approach. Also these animations can be shown when you tap that info icon in a separate view with a longer text description below the animation.

**Comment by jrpie** [comment]
> Also I checked others and they provide animations explaining some mechanics. I reckon these animations are much harder to implement, but I think that'll be the most helpful approach. Also these animations can be shown when you tap that info icon in a separate view with a longer text description below the animation.

Yes that would be very nice, but I don't have time unfortunately. I think it doesn't add enough value over explanatory texts to be worth the required time, I'd rather use that to implement features that are relevant to every day use.
(Also I'd like to keep the codebase as minimal as possible)

**Comment by jrpie** [comment]
> I think animations might also be useful to show where the edge areas are. Right now you can get that only through trial and error which is not very pleasant

Another hard coded value (15%) ...
I think adding an option for this might be worthwhile. While the user updates the slider, lines could indicate the actual dimensions of the edges.

**Comment by jrpie** [comment]
As those are two separate issues, I opened #55 and #56 and will close this one.
Might take a while until I have time to work on those.

For a broader discussion not related to a single issue I think the matrix or discord chat (the two are bridged together) would be a better place ^^
