### ISSUE TITLE
[feature] Configure swipe parameters

### ISSUE THREAD

**Issue by BANOnotIT** [jrpie/Launcher#54]
# Mandatory: Please describe the problem to be solved
Horizontal swipe seems to be slightly longer from what I'm used to. But there's no option to configure when it's triggered.

Would be great to have some ability to change it for horizontal and vertical direction independently to make it easier to transition to this great thing.

**Comment by jrpie** [comment]
Thanks for pointing that out!

The gesture detection is indeed asymmetrical and relies on some arbitrary constants. That should definitely not be the case.

Furthermore the current implementation depends on pixel density which is of course very bad.

The question is whether there are some values that work on every device.
The original app had an option for sensitivity and everybody I knew immediately set that to maximum. The current constants corresspond to that old maximum setting (which was just arbitrary).

Probably it is best to just use the [default value provided by android](https://developer.android.com/reference/android/view/ViewConfiguration#getScaledTouchSlop()). This seems to be very sensitive whilst still not detecting taps as swipes in random directions.

**Comment by BANOnotIT** [comment]
Yep, that's definitely much closer to what I personally am used to. Thanks!
