### ISSUE TITLE
[feature] add info text for "double actions"

### ISSUE THREAD

**Issue by jrpie** [jrpie/Launcher#55]
See #53 

> It means swiping with two fingers. I'm not too happy about the wording (also in other translations), maybe "two fingers up" might be better (?) Any other suggestion?
>
> The proplem is that the label needs to be somewhat short in order to fit an small screen. Another suggestion would be to keep the current labels and add an info icon with a more verbose description.

**Comment by BANOnotIT** [comment]
The problem with "short labels" also is that those can not be translated properly either to keep it short.

Double up would become
Двумя вверх in Russian for example.

**Comment by jrpie** [comment]
True. Perhaps I should modify the layout such that multi-line labels don't look as bad any more and then use longer, more descriptive labels. (There already is stuff like "swipe down (left edge)" which I don't know how to abbreviate any further)

An info icon would take up additional space and long click to display an info text might not be discovered.

**Comment by jrpie** [comment]
Perhaps tooltips might be a solution?

![Screenshot_20241101_234444](https://github.com/user-attachments/assets/2e330dfc-20ab-4383-a625-203b848574b4)

Perhaps the labels could then be shortened even further (i.e. just "Up" instead of "Swipe Up"). What do you think?

**Comment by jrpie** [comment]
Tooltips only exists since Android 8. I implemented the following alternative for older devices:

![Screenshot_20241102_001437](https://github.com/user-attachments/assets/22e348fd-a9b8-4cd9-a8ec-67321b092e3c)

So now on Android 8+ tooltips are shown, whereas older versions always show the description (as in the first suggestion)

**Comment by jrpie** [comment]
I'm not quite sure about the discoverability of tooltips. Maybe I should use the android < 8 solution on all versions. On the other hand I think it looks quite cluttered. Any opinions?

**Comment by BANOnotIT** [comment]
I personally am strongly against any "invisible" interactions. So I would rather go with Android <8 variant for all version, or (?) button that'll show more info. Lack of visual cues might be pretty troublesome for newbies.
