### ISSUE TITLE
[bug] Scroll position not saved after action is set

### ISSUE THREAD

**Issue by BANOnotIT** [jrpie/Launcher#57]
# Describe the bug
App does not save scroll position you were using before setting specific app to trigger

# To Reproduce
1. Go to Settings, App tab
2. Scroll down to "Double right" section
3. Tap "Chose App"
4. Select some app to be invoked

# Actual behavior
You are navigated back to the App tab but it is in Scroll=0 as if I just opened this section.

# Expected behavior
You are navigated back to the App tab with the same scroll and see "Double right" in the same place you left it.

# Smartphone (please complete the following information)
 - µLauncher Version: [e.g. j-0.0.12]

**Comment by jrpie** [comment]
That is indeed annoying, thanks for reporting, However there doesn't seem to be an easy fix and it doesn't impact every-day use too much, so I set this to low priority.
