### ISSUE TITLE
[bug] Swipe to previous App does not work

### ISSUE THREAD

**Issue by BANOnotIT** [jrpie/Launcher#58]
# Describe the bug
MUI implements bottom edge gestures similar to iPhone ones. And there is a gesture to open a previous application. I suppose this Launcher doesn't implement some interface to select which application to go to.

# To Reproduce
1. Open application A
2. Go to the home page
3. Open application B
4. Swipe right at the edge of the screen

# Expected behavior
Application A should be opened

# Screenshots
<details>
<summary>Expected behavior</summary>

https://github.com/user-attachments/assets/e64326e6-6044-4e15-aa6f-49a45f6541f5

</details>

# Smartphone (please complete the following information)
 - Device: Redmi Note 8 Pro
 - MUI: 12
 - Android Version: 10
 - µLauncher Version: j-0.0.12

# Additional info
Add any other info or comments about the problem here.

**Comment by jrpie** [comment]
Sorry, I don't quite understand the bug you are describing (I know neither MUI nor iOS).
What you describe sound like the default android 10 gesture navigation to me, does MUI implement this differently?

To clarify:

> 2. Go to the home page

i.e. µLauncher? How? By using a (MUI) gesture or pressing the home button?
If you use a different (preferably open source; not the MUI default, as that might do some MUI-specific stuff) home screen, everything works as expected?

> 4. Swipe right at the edge of the screen

This is the MUI gesture that should go to the previous app?

> Application A should be opened

What is happening instead?


In the video you uploaded, you only show the MUI gesture, right?

**Comment by BANOnotIT** [comment]
Was trying to create a setup and record µLauncher behavior, and it worked this time. 

I guess my phone just stopped the application I was trying to swipe to, hence there were no applications "in the stack".
