### ISSUE TITLE
[feature] Add a configurable margin of error for sliding

### ISSUE THREAD

**Issue by repomansez** [jrpie/Launcher#59]
#  Please describe the problem to be solved
I have many times tried to slide up or down and ended up registering as sliding to the sides, I think it would be neat if we had a configurable "margin of error" to maybe try and avoid that.

It is definitely more of a "me problem", but I thought maybe you guys would like the idea.

**Comment by jrpie** [comment]
Indeed, a gesture is never rejected and even a diagonal swipe will be classified as either vertical or horizontal.
I'd like to solve this without adding a (probably confusing) setting. IMO the best way is simply to reject gestures that are to far off from valid gestures

**Comment by repomansez** [comment]
> I implemented this in [6cabcf5](https://github.com/jrpie/Launcher/commit/6cabcf51bd78979377bf7a04d67081bc7a7936c3). Here is a [preview build](https://jrpie.de/downloads/launcher-test-gesture-tolerance-30deg.apk) in case you don't want to build it yourself.
> 
> What do you think about this solution?

Hi! I've been testing it and it has definitely improved it, but I think a more ideal solution would be something like, when it detects a diagonal scroll for example, compare if the person has dragged more pixels down or left/right, and activate that action. What do you think?

**Comment by jrpie** [comment]
> compare if the person has dragged more pixels down or left/right, and activate that action

That is precicely what the app did previously. In 6cabcf5 I simply added a check reject the gesture if the x and y direction of the swipe are close to each other (more precisely reject if `tan(30°) * |x| <= |y|` and `tan(30°) * |y| <= |x|`, 30° is admittedly somewhat arbitrary).

Maybe I missunderstood what you were trying to say?

**Comment by jrpie** [comment]
For comparing to the previous version it is probably best to use the preview build from [here](https://github.com/jrpie/Launcher/issues/54#issuecomment-2426652614) sine some other changes on the gesture detection have been made since the last release

**Comment by jrpie** [comment]
Any further comments? Otherwise I would close this

**Comment by repomansez** [comment]
Sorry for the holdup. In my opinion your change has indeed made it better :) 

I'm closing this issue.
