### ISSUE TITLE
[feature] launch favorites by default

### ISSUE THREAD

**Issue by yannickdoteu** [jrpie/Launcher#62]
# please describe the problem to be solved
The fact that I need to consciously look for an app before I can launch it is great and reduces the risk of sticking on my phone too long, but it would be even better if I had a way to incentivize myself to using 'good' apps on my launcher.

#  Describe the solution you would suggest
An easy way to enable this would be -- I think -- to enable an option in the settings for toggling the favourute star in the bottom right corner by default when opening the search tray with all apps. This way I can put all my 'good' apps in favourites and give them much more visibility than those bad apps that happen to start with an A, B, C ...

#  Describe alternative solutions you've considered

#  Additional info

**Comment by jrpie** [comment]
There exists an action "Favorite Apps" that works like that (i.e. it opens the same list as "All Apps" but favorites is toggles), so you can just bind that action to "Swipe Up" or whatever gesture you use.

I wouldn't want to change the default, as new users would then just see a confusing empty list.

(Admittedly this does not help if you use back to open the list, as back is currently not configurable. Perhaps I should change that, however I need to ensure that users can somehow reach the app settings again)

**Comment by yannickdoteu** [comment]
Ah yeah I admittedly haven't used the custom gestures settings so much, but this works perfect for me! Thanks :-D
