### ISSUE TITLE
[bug] Fingerprint and face recognition not working after lock screen action

### ISSUE THREAD

**Issue by RizkyM2999** [jrpie/Launcher#65]
# Discribe

when device locked by action fingerprint doesn't works it says "Device Locked by Admin".

# To Reproduce

1. Sett Lock screen action
2. Trigger it
3. Try to unlock with Fingerprint of Face recognition 

# Expected behavior

it should be working unlocking with fingerprint.

# Smartphone (please complete the following information)
 - Device:  Redmi Note 7 
 - Android Version:  A14 
 - µLauncher Version:  j-0.0.13

**Comment by RizkyM2999** [comment]
I think it's better to use accessibility to lock the screen like other launchers..🤔

**Comment by jrpie** [comment]
Thanks for pointing that out.

Accessibility is what @yzqzss originally proposed in #61 . My main arguments against that were that
(a) accessibility doesn't seem to have a way to specify what acces the app needs (and the dialog when activating it says something along the lines of "this gives µLauncher access to read from and interact with any other app")
(b) accessibility only works on newer devices.

I didn't see any arguments in favor of accessibility then. Not being able to unlock with fingerprint is of course a problem.

**Comment by RizkyM2999** [comment]
Yeah I know but there's no better solution except using Accessibility Service.. 
Like [@yzqzss](https://github.com/yzqzss) said it's common uses by other launcher

**Comment by jrpie** [comment]
I don't really feel comfortable with training users to grant that kind of power to an app for a relatively minor feature. (But then I also don't quite understand why people wanted this feature in the first place, there is a hardware button doing the same thing after all; so perhaps I erring too much towards viewing the feature as a useless gimmick)

Going forward I see three options:
1. Use device admin on older devices and accessibility on newer ones.
2. Switch to accessibility and drop support for this feature on older devices, keeping the codebase smaller.
3. Let users decide what to do and inform the about upsides and downsides of both approaches.

Since there are already implementations of both approaches, that shouldn't be too much work.

**Comment by RizkyM2999** [comment]
The first option seems good
Because for me and some people DT2S is crucial in the launcher, I'm personally using it for a long time so it's become a habit.

**Comment by jrpie** [comment]
Is it really so bad to bother the user with a dialog like this the first time they try to lock the screen?
![image](https://github.com/user-attachments/assets/82ee1738-332b-4fee-ba2a-8ad2ba2a5665)

To me this sound better than redirecting immediately to this
![image](https://github.com/user-attachments/assets/e7b40bd5-a47b-43fa-97f5-3bf7fe3556e9)

**Comment by RizkyM2999** [comment]
> Is it really so bad to bother the user with a dialog like this the first time they try to lock the screen? ![image](https://private-user-images.githubusercontent.com/30079494/382937004-82ee1738-332b-4fee-ba2a-8ad2ba2a5665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODA2NzgsIm5iZiI6MTczMDc4MDM3OCwicGF0aCI6Ii8zMDA3OTQ5NC8zODI5MzcwMDQtODJlZTE3MzgtMzMyYi00ZmVlLWJhMmEtOGFkMmJhMmE1NjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA0MTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMWRjNzE2M2Y5ZDUxYmNkYTJhODU3NmM0MjJmZmIxMjRlMjVjM2RiYmZjODYzZDM1NzU2YzQ2NWQ4YmY3NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sdQY1N59ADL6R6vvQJg_UeIKkiQugUdeqKqRPOuNBOA)
> 
It's good I think it's just a one time setup.
Or you can make that dialog comes up when the user sets the sleep action instead of when it is first triggered.
