### ISSUE TITLE
[feature] Renaming of Apps

### ISSUE THREAD

**Issue by Xanadul** [jrpie/Launcher#68]
#  Please describe the problem to be solved
Some apps are hard to find/autolaunch using search. Extreme example would be the former twitter app, now called "X". Since searching for X will return all apps including the letter X in the name and prevent the automatic launch of the actual X app.
Another example would be the "Nekogram" app, a telegram client. When wanting to write a telegram message in nekogram, one might type "Tele" into the search field, accidentaly opening the phone app. Renaming Nekogram to something like "Nekogram / Telegram" would fix this issue.

#  Describe the solution you would suggest
Being able to rename the apps in the launcher.
The "X" app could be renamed to "X.com" making it searchable and allowing auto launch just by typing "x."

#  Describe alternative solutions you've considered
Option of auto launching an app when its entire name is written in the search bar. Though in the example of "X", that might prevent serching for other apps starting with the letter X. Would not help with comfusing app names either.

#  Additional info
OlauncherCF has the requested feature. When holding down on an app name, the name changes into an editable textfield. Might be worth a look for comparison.

**Comment by jrpie** [comment]
Thanks for the suggestion, sounds useful to me! An alternative solution would be to let users set (multiple) aliases, but I think renaming is easier to implement, easier to explain to users and sufficient for most use cases.

**Comment by Xanadul** [comment]
Aliases sound great too. I would prefer them over renaming tbh. But I agree that renaming would be easiert to explain to users, suffices for most users and would definetly suffice for me too.
Also, I just noticed another advantage of renaming: Hiding apps via obfuscation. Some users might want to hide specific apps but keep them easily accesible. Aliases would not work for this usecase.
