### ISSUE TITLE
[bug] Can select apps "behind" the keyboard 

### ISSUE THREAD

**Issue by kaelanryder** [jrpie/Launcher#90]
# Describe the bug

On the apps list (list, unchecked on the grid), if one goes to search an application, the first letter can be entered normally; however on tapping on the second letter on the first row of keyboard, whatever application is on the list "behind" the keyboard gets selected and is opened, hence making searching for apps very hard

# To Reproduce

1. Open apps list
2. Tap on "Search Applications"
3. Keyboard pops up, enter the first letter
4. Tap on any second letter (only in the first row of the keyboard)
5. See error

# Expected behavior

Expected the launcher to keep searching and not launch an app

# Screenshots
Can't add screenshots for this one sorry 

# Smartphone (please complete the following information)
 - Device: Google Pixel 4
 - Android Version: Android 13 (TP1A.221005.002.B2)
 - µLauncher Version: j-0.0.18

# Additional info

**Comment by jrpie** [comment]
Thanks for reporting!

Could you please send a screenshot? There should not be any apps behind the keyboard, the view should resize to make space for the keyboard.

Are you sure this is not the auto-launch feature?
(Settings > Launcher > Functionality > Launch search results)

**Comment by wassupluke** [comment]
And what keyboard are you using?
(Probably somewhere similar to Settings>System>Keyboard>On-screen Keyboard)

**Comment by kaelanryder** [comment]
Hi yes,
I'm so sorry it seems my brain farted. It was just the "Launch search results" setting in the launcher and I couldn't figure it out. Coincidentally, the app that was opening was also just behind that tap area on the keyboard; leading me to misjudged the situation. 
Again so sorry for wasting your time if I did any.

**Comment by jrpie** [comment]
Perhaps the feature should be mentioned in the tutorial?

**Comment by kaelanryder** [comment]
Yes absolutely, it's an ingenious launcher & it would be just wrong if someone decided to give it up because of this small thing; because I remember it being really annoying when I encountered it.
